### ISSUE TITLE
consumption returns None

### ISSUE THREAD

**Issue by btuysser** [rsnodgrass/pyflowater#1]
--Consumption--
pyflowater - INFO - Loading https://api-gw.meetflo.com/api/v2/water/consumption
pyflowater - DEBUG - Params: {'locationId': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx', 'startDate': '2020-01-20T08:00:00.000Z', 'endDate': '2020-01-21T08:00:00.000Z', 'interval': '1h'}
pyflowater - DEBUG - Headers: {'User-Agent': 'PyFlo (https://github.com/rsnodgrass/pyflowater/)', 'Content-Type': 'application/json;charset=UTF-8', 'Accept': 'application/json', 'authorization': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'}
pyflowater - DEBUG - Querying https://api-gw.meetflo.com/api/v2/water/consumption on attempt: 1/3
urllib3.connectionpool - DEBUG - https://api-gw.meetflo.com:443 "GET /api/v2/water/consumption HTTP/1.1" 403 36
pyflowater - DEBUG - Params: {'locationId': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx', 'startDate': '2020-01-20T08:00:00.000Z', 'endDate': '2020-01-21T08:00:00.000Z', 'interval': '1h'}
pyflowater - DEBUG - Headers: {'User-Agent': 'PyFlo (https://github.com/rsnodgrass/pyflowater/)', 'Content-Type': 'application/json;charset=UTF-8', 'Accept': 'application/json', 'authorization': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'}
pyflowater - DEBUG - Querying https://api-gw.meetflo.com/api/v2/water/consumption on attempt: 2/3
urllib3.connectionpool - DEBUG - https://api-gw.meetflo.com:443 "GET /api/v2/water/consumption HTTP/1.1" 403 36
pyflowater - DEBUG - Params: {'locationId': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx', 'startDate': '2020-01-20T08:00:00.000Z', 'endDate': '2020-01-21T08:00:00.000Z', 'interval': '1h'}
pyflowater - DEBUG - Headers: {'User-Agent': 'PyFlo (https://github.com/rsnodgrass/pyflowater/)', 'Content-Type': 'application/json;charset=UTF-8', 'Accept': 'application/json', 'authorization': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'}
pyflowater - DEBUG - Querying https://api-gw.meetflo.com/api/v2/water/consumption on attempt: 3/3
urllib3.connectionpool - DEBUG - https://api-gw.meetflo.com:443 "GET /api/v2/water/consumption HTTP/1.1" 403 36
pyflowater - DEBUG - Params: {'locationId': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx', 'startDate': '2020-01-20T08:00:00.000Z', 'endDate': '2020-01-21T08:00:00.000Z', 'interval': '1h'}
pyflowater - DEBUG - Headers: {'User-Agent': 'PyFlo (https://github.com/rsnodgrass/pyflowater/)', 'Content-Type': 'application/json;charset=UTF-8', 'Accept': 'application/json', 'authorization': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'}
pyflowater - DEBUG - Querying https://api-gw.meetflo.com/api/v2/water/consumption on attempt: 4/3
urllib3.connectionpool - DEBUG - https://api-gw.meetflo.com:443 "GET /api/v2/water/consumption HTTP/1.1" 403 36
None

**Comment by btuysser** [comment]
Looks like there is an id per location and an id per device. The consumption api requires the location id in the request rather than the device id. Also the query method needed to add extra params to the get request.

**Comment by btuysser** [comment]
https://github.com/rsnodgrass/pyflowater/pull/2

**Comment by rsnodgrass** [comment]
Thanks @btuysser for troubleshooting and fixing!
