### ISSUE TITLE
"invalid syntax" when running with python3.5

### ISSUE THREAD

**Issue by rajid** [rsnodgrass/pyflowater#20]
I installed "pip3", used it to install "python3.5", installed this package, then ran the example code (after defining FLO_USER and FLO_PASSWORD in environment).  No matter what I try, I keep getting:

  File "/usr/local/lib/python3.5/dist-packages/pyflowater/__init__.py", line 76
    LOG.debug(f"Authenticating Flo account {self._username} via {FLO_AUTH_URL}")
                                                                              ^
SyntaxError: invalid syntax

I'm sure it has something to do with my installation and isn't an error in the code, but I can't seem to find any help on this elsewhere on the net.   I'm hoping someone can point me to something which clarifies the matter on which I'm obviously just being stupid!

**Comment by rsnodgrass** [comment]
Try python3.9

--

**Comment by rajid** [comment]
Ok, I have installed Python3.9 but now I'm being told I need glibc 2.33:

ImportError: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.33' not found (required by /usr/lib/python3.9/site-packages/grpcio-1.42.0rc1-py3.9-linux-armv7l.egg/grpc/_cython/cygrpc.cpython-39-arm-linux-gnueabihf.so)

It looks as if I'll have to install this from source.  Apparently, version 2.24 is the standard one for this version of Debian.

**Comment by rajid** [comment]
Installing glibc 2.33 from source failed and it's not clear how to make it work.

Inconsistency detected by ld.so: dl-call-libc-early-init.c: 37: _dl_call_libc_early_init: Assertion `sym != NULL' failed!

This is now effecting all programs which use glibc, which is basically everything on the system.  I'll have to reinstall the OS.

I'm just going to close this issue and I'll write my own API interface using the information here on how to access the info.  I think that'll be easier.  Thanks for the help!
