### ISSUE TITLE
aioflo

### ISSUE THREAD

**Issue by squirrel289** [rsnodgrass/pyflowater#3]
I found this repo because of your home assistant integration, which I am starting to use now.  Thank you for all of your work on that! When I saw the limitations for that integration I began searching for documentation and/or libraries that implemented the missing functionality (mode, on/off, etc). That’s when I came across aioflo ( https://github.com/bachya/aioflo). I’m wondering if you have seen it and/or been in contact with bachya to see about combining efforts.

Anyway, I really appreciate the work you’ve done to integrate flo!

**Comment by rsnodgrass** [comment]
Thanks for letting me know, I had not seen aioflo!

**Comment by rsnodgrass** [comment]
FYI, pyflowater does implement modes, on/off, etc. already...I need to
check that the Home Assistant integration actually calls them successfully.
